# RULES
trigger := binding , command_trigger | signal_trigger , eof;
binding := lp , input , rp , arrow;
signal_trigger := signal , command_trigger;
signal := pi , input , pi , arrow;
command_trigger := payload , [ mode ];
payload := lc , input , rc , arrow;
mode := lb , input , rb;
input := { char , escape | char };

# TOKENS
arrow := "-" , ">";
escape := "\";
lb := "[";
lc := "{";
lp := "(";
pi := "|";
rb := "]";
rc := "}";
rp := ")";

# GENERAL
char := (any character);
eof := (end of file);

